# makefile
# project: counter
# melvin.alvarado

SRC_VERIF = counter_pkg.sv counter_tb_top.sv
SRC_RTL = counter.v
TB_TOP = counter_tb_top
DEFINE = ASSERT_ON COVERAGE_ON

SIM_OPT = --testplusarg UVM_TESTNAME=counter_test

include $(CODE)/makefiles/vivado.mk