# makefile
# project: uvm-tutorial
# melvin.alvarado

SRC_VERIF = simpleadder_tb_top.sv \
	simpleadder_pkg.sv

SRC_RTL = simpleadder.v
TB_TOP = simpleadder_tb_top
#DEFINE = ASSERT_ON COVERAGE_ON

SIM_OPT = --testplusarg UVM_TESTNAME=simpleadder_test

include $(CODE)/makefiles/vivado.mk