# makefile
# project: mem-control
# melvin.alvarado

SRC_VERIF = testbench.sv
SRC_RTL = design.sv
TB_TOP = tb_top

#COMP_RTL_OPT = --incr
SIM_OPT = --testplusarg UVM_TESTNAME=test_basic

include $(CODE)/makefiles/vivado.mk