# makefile
# project: regs
# melvin.alvarado

SRC_VERIF = tb.v
SRC_RTL = regs.v
SRC_RTL_EXTRA = $(COMMON)/rtl/common.vh
TB_TOP = tb
#DEFINE = ASSERT_ON COVERAGE_ON

include $(CODE)/makefiles/vivado.mk