# makefile
# project: counter
# melvin.alvarado

SRC_VERIF = counter_if.sv counter_pkg.svh tb.v
SRC_RTL = counter.v
TB_TOP = tb
#DEFINE = ASSERT_ON COVERAGE_ON

SIM_OPT = --testplusarg UVM_TESTNAME=counter_test


include $(CODE)/makefiles/vivado.mk