# makefile
# project: control-fsm
# melvin.alvarado

SRC_VERIF = tb.sv
SRC_RTL = control.v
TB_TOP = tb
#DEFINE = ASSERT_ON COVERAGE_ON

SIM_OPT = --testplusarg UVM_TESTNAME=control_test

include $(CODE)/makefiles/vivado.mk